/*******************************************************************************
 * Copyright 2012 David Rusk 
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); 
 * you may not use this file except in compliance with the License. 
 * You may obtain a copy of the License at 
 *
 *    http://www.apache.org/licenses/LICENSE-2.0 
 *     
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License.  
 *******************************************************************************/
package org.thechiselgroup.biomixer.client.visualization_component.graph.widget;

import org.junit.Test;
import org.thechiselgroup.biomixer.client.core.geometry.Point;

/**
 * This class tests the SVG generated by the GraphSvgDisplay. Unit tests for
 * methods which do not result in SVG output are in GraphSvgDisplayProcessTest.
 * 
 * @author drusk
 * 
 */
public class GraphSvgDisplayOutputTest extends AbstractGraphSvgDisplayTest {

    @Test
    public void addNodePutsRectangleInSvg() {
        addNode(ID1, LABEL1, TYPE);
        assertSvgElementEqualsFile("addSingleNode", underTest.asSvg());
    }

    @Test
    public void addTwoNodesAddArcSetLocationShouldCauseArcToReposition() {
        addNode(ID1, LABEL1, TYPE);
        Node node2 = new Node(ID2, LABEL2, TYPE);
        underTest.addNode(node2);
        addArc(ARC_ID1, ID1, ID2, TYPE, true);
        underTest.setLocation(node2, new Point(130, 0));
        assertSvgElementEqualsFile("twoNodesOneArc", underTest.asSvg());
    }

    @Test
    public void addTwoNodesAndSetNewLocation() {
        Node node1 = new Node(ID1, LABEL1, TYPE);
        Node node2 = new Node(ID2, LABEL2, TYPE);
        underTest.addNode(node1);
        underTest.addNode(node2);
        underTest.setLocation(node2, new Point(130, 0));
        assertSvgElementEqualsFile("addTwoNodesSetLocation", underTest.asSvg());
    }

    @Test
    public void addTwoNodesPutsRectanglesInSvg() {
        addNode(ID1, LABEL1, TYPE);
        addNode(ID2, LABEL2, TYPE);
        assertSvgElementEqualsFile("addTwoNodes", underTest.asSvg());
    }

    @Test
    public void addTwoNodesRemoveOne() {
        Node node1 = new Node(ID1, LABEL1, TYPE);
        Node node2 = new Node(ID2, LABEL2, TYPE);
        underTest.addNode(node1);
        underTest.addNode(node2);
        underTest.removeNode(node1);
        assertSvgElementEqualsFile("addTwoNodesRemoveOne", underTest.asSvg());
    }

    @Test
    public void addTwoNodesSetLocationAddArc() {
        addNode(ID1, LABEL1, TYPE);
        Node node2 = new Node(ID2, LABEL2, TYPE);
        underTest.addNode(node2);
        underTest.setLocation(node2, new Point(130, 0));
        addArc(ARC_ID1, ID1, ID2, TYPE, true);
        assertSvgElementEqualsFile("twoNodesOneArc", underTest.asSvg());
    }

    @Test
    public void removeArcBetweenTwoNodes() {
        addNode(ID1, LABEL1, TYPE);
        Node node2 = new Node(ID2, LABEL2, TYPE);
        underTest.addNode(node2);
        underTest.setLocation(node2, new Point(130, 0));
        Arc arc = new Arc(ARC_ID1, ID1, ID2, TYPE, true);
        underTest.addArc(arc);
        underTest.removeArc(arc);
        assertSvgElementEqualsFile("addTwoNodesSetLocation", underTest.asSvg());
    }

    @Test
    public void removingNodeShouldRemoveArc() {
        Node node1 = new Node(ID1, LABEL1, TYPE);
        Node node2 = new Node(ID2, LABEL2, TYPE);
        underTest.addNode(node1);
        underTest.addNode(node2);
        Arc arc = new Arc(ARC_ID1, ID1, ID2, TYPE, true);
        underTest.addArc(arc);
        underTest.setLocation(node2, new Point(130, 0));
        underTest.removeNode(node1);
        assertSvgElementEqualsFile("addTwoNodesAddArcMoveNode2RemoveNode1",
                underTest.asSvg());
    }

}
